name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ensure correct Node.js version

      - name: Verify Node.js Version
        run: node -v  # Check that Node.js 18+ is correctly installed

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
        run: |
          firebase use --add the-clean-credit-academy
          firebase deploy --only hosting --token "$FIREBASE_DEPLOY_TOKEN"
